#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# BCM56990 system port configuration.
#
#
---
device:
    0:
        PC_PORT_PHYS_MAP:
            ?
                PORT_ID: 0
            :
                PC_PHYS_PORT_ID: 0
            ?
                PORT_ID: 33
            :
                PC_PHYS_PORT_ID: 259
            ?
                PORT_ID: 67
            :
                PC_PHYS_PORT_ID: 260
            ?
                PORT_ID: 101
            :
                PC_PHYS_PORT_ID: 261
            ?
                PORT_ID: 135
            :
                PC_PHYS_PORT_ID: 262
            ?
                PORT_ID: 169
            :
                PC_PHYS_PORT_ID: 263
            ?
                PORT_ID: 203
            :
                PC_PHYS_PORT_ID: 264
            ?
                PORT_ID: 237
            :
                PC_PHYS_PORT_ID: 265
            ?
                PORT_ID: 271
            :
                PC_PHYS_PORT_ID: 266
...
---
device:
    0:
        PC_PORT:
            ?
                PORT_ID: [0, 33, 67, 101, 135,
                          169, 203, 237, 271]
            :
                ENABLE: 1
                SPEED: 10000
                NUM_LANES: 1
...
