#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# BCM56997 96x100g+8x400G port configuration.
# Support pipe numbers: 0, 1, 2, 3, 12, 13, 14, 15
#
# configuration yaml file
#   device:
#       <unit>:
#           <table>:
#               ?
#                   <key_fld_1>: <value>
#                   <key_fld_2>: <value>
#                   ...
#                   <key_fld_n>: <value>
#               :
#                   <data_fld_1>: <value>
#                   <data_fld_2>: <value>
#                   ...
#                   <data_fld_n>: <value>
#

---
device:
    0:
        PC_PORT_PHYS_MAP:
            ?
                PORT_ID: 1
            :
                PC_PHYS_PORT_ID: 1
            ?
                PORT_ID: 2
            :
                PC_PHYS_PORT_ID: 5
            ?
                PORT_ID: 3
            :
                PC_PHYS_PORT_ID: 6
            ?
                PORT_ID: 4
            :
                PC_PHYS_PORT_ID: 7
            ?
                PORT_ID: 5
            :
                PC_PHYS_PORT_ID: 8
            ?
                PORT_ID: 6
            :
                PC_PHYS_PORT_ID: 9
            ?
                PORT_ID: 7
            :
                PC_PHYS_PORT_ID: 10
            ?
                PORT_ID: 8
            :
                PC_PHYS_PORT_ID: 11
            ?
                PORT_ID: 9
            :
                PC_PHYS_PORT_ID: 12
            ?
                PORT_ID: 10
            :
                PC_PHYS_PORT_ID: 13
            ?
                PORT_ID: 11
            :
                PC_PHYS_PORT_ID: 14
            ?
                PORT_ID: 12
            :
                PC_PHYS_PORT_ID: 15
            ?
                PORT_ID: 13
            :
                PC_PHYS_PORT_ID: 16
            ?
                PORT_ID: 17     # Pipe1
            :
                PC_PHYS_PORT_ID: 17
            ?
                PORT_ID: 18
            :
                PC_PHYS_PORT_ID: 21
            ?
                PORT_ID: 19
            :
                PC_PHYS_PORT_ID: 22
            ?
                PORT_ID: 20
            :
                PC_PHYS_PORT_ID: 23
            ?
                PORT_ID: 21
            :
                PC_PHYS_PORT_ID: 24
            ?
                PORT_ID: 22
            :
                PC_PHYS_PORT_ID: 25
            ?
                PORT_ID: 23
            :
                PC_PHYS_PORT_ID: 26
            ?
                PORT_ID: 24
            :
                PC_PHYS_PORT_ID: 27
            ?
                PORT_ID: 25
            :
                PC_PHYS_PORT_ID: 28
            ?
                PORT_ID: 26
            :
                PC_PHYS_PORT_ID: 29
            ?
                PORT_ID: 27
            :
                PC_PHYS_PORT_ID: 30
            ?
                PORT_ID: 28
            :
                PC_PHYS_PORT_ID: 31
            ?
                PORT_ID: 29
            :
                PC_PHYS_PORT_ID: 32
            ?
                PORT_ID: 34     # Pipe2
            :
                PC_PHYS_PORT_ID: 33
            ?
                PORT_ID: 35
            :
                PC_PHYS_PORT_ID: 37
            ?
                PORT_ID: 36
            :
                PC_PHYS_PORT_ID: 38
            ?
                PORT_ID: 37
            :
                PC_PHYS_PORT_ID: 39
            ?
                PORT_ID: 38
            :
                PC_PHYS_PORT_ID: 40
            ?
                PORT_ID: 39
            :
                PC_PHYS_PORT_ID: 41
            ?
                PORT_ID: 40
            :
                PC_PHYS_PORT_ID: 42
            ?
                PORT_ID: 41
            :
                PC_PHYS_PORT_ID: 43
            ?
                PORT_ID: 42
            :
                PC_PHYS_PORT_ID: 44
            ?
                PORT_ID: 43
            :
                PC_PHYS_PORT_ID: 45
            ?
                PORT_ID: 44
            :
                PC_PHYS_PORT_ID: 46
            ?
                PORT_ID: 45
            :
                PC_PHYS_PORT_ID: 47
            ?
                PORT_ID: 46
            :
                PC_PHYS_PORT_ID: 48
            ?
                PORT_ID: 51     # Pipe3
            :
                PC_PHYS_PORT_ID: 49
            ?
                PORT_ID: 52
            :
                PC_PHYS_PORT_ID: 53
            ?
                PORT_ID: 53
            :
                PC_PHYS_PORT_ID: 54
            ?
                PORT_ID: 54
            :
                PC_PHYS_PORT_ID: 55
            ?
                PORT_ID: 55
            :
                PC_PHYS_PORT_ID: 56
            ?
                PORT_ID: 56
            :
                PC_PHYS_PORT_ID: 57
            ?
                PORT_ID: 57
            :
                PC_PHYS_PORT_ID: 58
            ?
                PORT_ID: 58
            :
                PC_PHYS_PORT_ID: 59
            ?
                PORT_ID: 59
            :
                PC_PHYS_PORT_ID: 60
            ?
                PORT_ID: 60
            :
                PC_PHYS_PORT_ID: 61
            ?
                PORT_ID: 61
            :
                PC_PHYS_PORT_ID: 62
            ?
                PORT_ID: 62
            :
                PC_PHYS_PORT_ID: 63
            ?
                PORT_ID: 63
            :
                PC_PHYS_PORT_ID: 64
            ?
                PORT_ID: 204    # Pipe12
            :
                PC_PHYS_PORT_ID: 193
            ?
                PORT_ID: 205
            :
                PC_PHYS_PORT_ID: 197
            ?
                PORT_ID: 206
            :
                PC_PHYS_PORT_ID: 198
            ?
                PORT_ID: 207
            :
                PC_PHYS_PORT_ID: 199
            ?
                PORT_ID: 208
            :
                PC_PHYS_PORT_ID: 200
            ?
                PORT_ID: 209
            :
                PC_PHYS_PORT_ID: 201
            ?
                PORT_ID: 210
            :
                PC_PHYS_PORT_ID: 202
            ?
                PORT_ID: 211
            :
                PC_PHYS_PORT_ID: 203
            ?
                PORT_ID: 212
            :
                PC_PHYS_PORT_ID: 204
            ?
                PORT_ID: 213
            :
                PC_PHYS_PORT_ID: 205
            ?
                PORT_ID: 214
            :
                PC_PHYS_PORT_ID: 206
            ?
                PORT_ID: 215
            :
                PC_PHYS_PORT_ID: 207
            ?
                PORT_ID: 216
            :
                PC_PHYS_PORT_ID: 208
            ?
                PORT_ID: 221    # Pipe13
            :
                PC_PHYS_PORT_ID: 209
            ?
                PORT_ID: 222
            :
                PC_PHYS_PORT_ID: 213
            ?
                PORT_ID: 223
            :
                PC_PHYS_PORT_ID: 214
            ?
                PORT_ID: 224
            :
                PC_PHYS_PORT_ID: 215
            ?
                PORT_ID: 225
            :
                PC_PHYS_PORT_ID: 216
            ?
                PORT_ID: 226
            :
                PC_PHYS_PORT_ID: 217
            ?
                PORT_ID: 227
            :
                PC_PHYS_PORT_ID: 218
            ?
                PORT_ID: 228
            :
                PC_PHYS_PORT_ID: 219
            ?
                PORT_ID: 229
            :
                PC_PHYS_PORT_ID: 220
            ?
                PORT_ID: 230
            :
                PC_PHYS_PORT_ID: 221
            ?
                PORT_ID: 231
            :
                PC_PHYS_PORT_ID: 222
            ?
                PORT_ID: 232
            :
                PC_PHYS_PORT_ID: 223
            ?
                PORT_ID: 233
            :
                PC_PHYS_PORT_ID: 224
            ?
                PORT_ID: 238    # Pipe14
            :
                PC_PHYS_PORT_ID: 225
            ?
                PORT_ID: 239
            :
                PC_PHYS_PORT_ID: 229
            ?
                PORT_ID: 240
            :
                PC_PHYS_PORT_ID: 230
            ?
                PORT_ID: 241
            :
                PC_PHYS_PORT_ID: 231
            ?
                PORT_ID: 242
            :
                PC_PHYS_PORT_ID: 232
            ?
                PORT_ID: 243
            :
                PC_PHYS_PORT_ID: 233
            ?
                PORT_ID: 244
            :
                PC_PHYS_PORT_ID: 234
            ?
                PORT_ID: 245
            :
                PC_PHYS_PORT_ID: 235
            ?
                PORT_ID: 246
            :
                PC_PHYS_PORT_ID: 236
            ?
                PORT_ID: 247
            :
                PC_PHYS_PORT_ID: 237
            ?
                PORT_ID: 248
            :
                PC_PHYS_PORT_ID: 238
            ?
                PORT_ID: 249
            :
                PC_PHYS_PORT_ID: 239
            ?
                PORT_ID: 250
            :
                PC_PHYS_PORT_ID: 240
            ?
                PORT_ID: 255    # Pipe15
            :
                PC_PHYS_PORT_ID: 241
            ?
                PORT_ID: 256
            :
                PC_PHYS_PORT_ID: 245
            ?
                PORT_ID: 257
            :
                PC_PHYS_PORT_ID: 246
            ?
                PORT_ID: 258
            :
                PC_PHYS_PORT_ID: 247
            ?
                PORT_ID: 259
            :
                PC_PHYS_PORT_ID: 248
            ?
                PORT_ID: 260
            :
                PC_PHYS_PORT_ID: 249
            ?
                PORT_ID: 261
            :
                PC_PHYS_PORT_ID: 250
            ?
                PORT_ID: 262
            :
                PC_PHYS_PORT_ID: 251
            ?
                PORT_ID: 263
            :
                PC_PHYS_PORT_ID: 252
            ?
                PORT_ID: 264
            :
                PC_PHYS_PORT_ID: 253
            ?
                PORT_ID: 265
            :
                PC_PHYS_PORT_ID: 254
            ?
                PORT_ID: 266
            :
                PC_PHYS_PORT_ID: 255
            ?
                PORT_ID: 267
            :
                PC_PHYS_PORT_ID: 256
...
---
device:
    0:
        PC_PORT:
            ?
                PORT_ID: [1, 17, 34, 51,
                          204, 221, 238, 255]
            :
                ENABLE: 1
                SPEED: 400000
                NUM_LANES: 4
                FEC_MODE: PC_FEC_RS544_2XN
                MAX_FRAME_SIZE: 9416
            ?
                PORT_ID: [[2, 13],
                          [18, 29],
                          [35, 46],
                          [52, 63],
                          [205, 216],
                          [222, 233],
                          [239, 250],
                          [256, 267]]
            :
                ENABLE: 1
                SPEED: 100000
                NUM_LANES: 1
                FEC_MODE: PC_FEC_RS544
                MAX_FRAME_SIZE: 9416
...
