#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# BCM56997 32x400g port configuration.
# Support pipe numbers: 0, 1, 2, 3, 12, 13, 14, 15
#
# configuration yaml file
#   device:
#       <unit>:
#           <table>:
#               ?
#                   <key_fld_1>: <value>
#                   <key_fld_2>: <value>
#                   ...
#                   <key_fld_n>: <value>
#               :
#                   <data_fld_1>: <value>
#                   <data_fld_2>: <value>
#                   ...
#                   <data_fld_n>: <value>
#

---
device:
    0:
        PC_PORT_PHYS_MAP:
            ?
                PORT_ID: 1
            :
                PC_PHYS_PORT_ID: 1
            ?
                PORT_ID: 2
            :
                PC_PHYS_PORT_ID: 5
            ?
                PORT_ID: 3
            :
                PC_PHYS_PORT_ID: 9
            ?
                PORT_ID: 4
            :
                PC_PHYS_PORT_ID: 13
            ?
                PORT_ID: 17
            :
                PC_PHYS_PORT_ID: 17
            ?
                PORT_ID: 18
            :
                PC_PHYS_PORT_ID: 21
            ?
                PORT_ID: 19
            :
                PC_PHYS_PORT_ID: 25
            ?
                PORT_ID: 20
            :
                PC_PHYS_PORT_ID: 29
            ?
                PORT_ID: 34
            :
                PC_PHYS_PORT_ID: 33
            ?
                PORT_ID: 35
            :
                PC_PHYS_PORT_ID: 37
            ?
                PORT_ID: 36
            :
                PC_PHYS_PORT_ID: 41
            ?
                PORT_ID: 37
            :
                PC_PHYS_PORT_ID: 45
            ?
                PORT_ID: 51
            :
                PC_PHYS_PORT_ID: 49
            ?
                PORT_ID: 52
            :
                PC_PHYS_PORT_ID: 53
            ?
                PORT_ID: 53
            :
                PC_PHYS_PORT_ID: 57
            ?
                PORT_ID: 54
            :
                PC_PHYS_PORT_ID: 61
            ?
                PORT_ID: 204
            :
                PC_PHYS_PORT_ID: 193
            ?
                PORT_ID: 205
            :
                PC_PHYS_PORT_ID: 197
            ?
                PORT_ID: 206
            :
                PC_PHYS_PORT_ID: 201
            ?
                PORT_ID: 207
            :
                PC_PHYS_PORT_ID: 205
            ?
                PORT_ID: 221
            :
                PC_PHYS_PORT_ID: 209
            ?
                PORT_ID: 222
            :
                PC_PHYS_PORT_ID: 213
            ?
                PORT_ID: 223
            :
                PC_PHYS_PORT_ID: 217
            ?
                PORT_ID: 224
            :
                PC_PHYS_PORT_ID: 221
            ?
                PORT_ID: 238
            :
                PC_PHYS_PORT_ID: 225
            ?
                PORT_ID: 239
            :
                PC_PHYS_PORT_ID: 229
            ?
                PORT_ID: 240
            :
                PC_PHYS_PORT_ID: 233
            ?
                PORT_ID: 241
            :
                PC_PHYS_PORT_ID: 237
            ?
                PORT_ID: 255
            :
                PC_PHYS_PORT_ID: 241
            ?
                PORT_ID: 256
            :
                PC_PHYS_PORT_ID: 245
            ?
                PORT_ID: 257
            :
                PC_PHYS_PORT_ID: 249
            ?
                PORT_ID: 258
            :
                PC_PHYS_PORT_ID: 253
...
---
device:
    0:
        PC_PORT:
            ?
                PORT_ID: [[1, 4],
                          [17, 20],
                          [34, 37],
                          [51, 54],
                          [204, 207],
                          [221, 224],
                          [238, 241],
                          [255, 258]]
            :
                ENABLE: 1
                SPEED: 400000
                NUM_LANES: 4
                FEC_MODE: PC_FEC_RS544_2XN
                MAX_FRAME_SIZE: 9416
...
